config/routes.rb
Rails.application.routes.draw do
  resources :gata_pages
  get 'hello/index'
  get 'hello/login_check'
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gata_page.rb
class GataPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gata_pages_controller.rb
class GataPagesController < ApplicationController
  before_action :set_gata_page, only: %i[ show edit update destroy ]

  # GET /gata_pages or /gata_pages.json
  def index
    @gata_pages = GataPage.page params[:page]
  end

  # GET /gata_pages/1 or /gata_pages/1.json
  def show
  end

  # GET /gata_pages/new
  def new
    @gata_page = GataPage.new
  end

  # GET /gata_pages/1/edit
  def edit
  end

  # POST /gata_pages or /gata_pages.json
  def create
    @gata_page = GataPage.new(gata_page_params)

    respond_to do |format|
      if @gata_page.save
        format.html { redirect_to gata_page_url(@gata_page), notice: "Gata page was successfully created." }
        format.json { render :show, status: :created, location: @gata_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gata_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gata_pages/1 or /gata_pages/1.json
  def update
    respond_to do |format|
      if @gata_page.update(gata_page_params)
        format.html { redirect_to gata_page_url(@gata_page), notice: "Gata page was successfully updated." }
        format.json { render :show, status: :ok, location: @gata_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gata_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gata_pages/1 or /gata_pages/1.json
  def destroy
    @gata_page.destroy

    respond_to do |format|
      format.html { redirect_to gata_pages_url, notice: "Gata page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gata_page
      @gata_page = GataPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gata_page_params
      params.require(:gata_page).permit(:data)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'application'
  before_action :authenticate_account!, only: :login_check
  
  def index
    @msg = 'this is sample page.'
  end

  def login_check
    @account = current_account
    @msg = 'account created at: ' + @account.created_at.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gata_pages_helper.rb
module GataPagesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/gata_pages/_form.html.erb
<%= form_with(model: gata_page, local: true) do |form| %>
  <% if gata_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gata_page.errors.count, "error") %> prohibited this gata_page from being saved:</h2>

      <ul>
      <% gata_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gata_pages/edit.html.erb
<h1>Editing Gata Page</h1>

<%= render 'form', gata_page: @gata_page %>

<%= link_to 'Show', @gata_page %> |
<%= link_to 'Back', gata_pages_path %>

app/views/gata_pages/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="display-4 text-primary">
  Data Pages</h1>
  
<div class='mt-4 mb-4'>
  <%= page_entries_info @gata_pages %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Data</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gata_pages.each do |gata_page| %>
      <tr>
        <td><%= gata_page.id %></td>
        <td><%= gata_page.data %></td>
        <td><%= gata_page.created_at %></td>
        <td><%= link_to 'Show', gata_page %></td>
        <td><%= link_to 'Edit', edit_gata_page_path(gata_page) %></td>
        <td><%= link_to 'Destroy', gata_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div><%= paginate @gata_pages %></div>
<br>

<%= link_to 'New Gata Page', new_gata_page_path %>

app/views/gata_pages/new.html.erb
<h1>New Gata Page</h1>

<%= render 'form', gata_page: @gata_page %>

<%= link_to 'Back', gata_pages_path %>

app/views/gata_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @gata_page.data %>
</p>

<%= link_to 'Edit', edit_gata_page_path(@gata_page) %> |
<%= link_to 'Back', gata_pages_path %>

app/views/hello/index.html.erb
<h1 class="display-4 text-primary">
  Hello#index</h1>
<p><%= @msg %></p>
<hr>
 <div><%=link_to 'login_check page !&gt;&gt;'.html_safe,
      {action:'login_check'} %></div>
 <div><%= link_to "sign out&gt;&gt;".html_safe, destroy_account_session_path, method: :delete %></div> 

app/views/hello/login_check.html.erb
<h1 class="display-4 text-primary">
  <%= @account.email %></h1>
<P><%= @msg %></P>
<hr>
<div><%=link_to '&lt;&lt;go back'.html_safe,
     {action:'index'} %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDeviseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"
         href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
         <%= stylesheet_link_tag 'application', media: 'all',
             'data-turbolinks-track': 'reload' %>
         <%= javascript_tag 'application',
             'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container text-body">
    <%= yield %>
  </body>
</html>